eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZobe: http://localhost:8761/eureka
server:
  port: 8070
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/schools?currentSchema=schools
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
application:
  config:
    students-url: http://localhost:8222/api/v1/students
management:
  tracing:
    sampling:
      probability: 1.0

